repo: openworm/openworm_docs
shortDescription: "Documentation for OpenWorm"
contributor-guide: "http://docs.openworm.org/en/latest/#contributing-to-openworm"
coordinator: stephen@openworm.org
keywords: 
  - readthedocs
  - documenation
languages: 
  - markdown
parent: 
  - openworm/OpenWorm
